### ISSUE TITLE
using latex node or edge labels

### ISSUE THREAD

**Issue by galenwilkerson** [chebee7i/nxpd#12]
Hi, useful project, thanks! 
Is it possible to use latex for node or edge labels?

```
G = nx.MultiDiGraph(with_labels=False,rankdir='LR')
G.graph['dpi'] = 120
G.add_node(1,label=r"$\sigma_1$",shape = 'circle')
G.add_node(2,label=r"$\sigma_2$",shape = 'circle')
G.add_edge(1,1,headport='nw',tailport='sw',label='sp')
G.add_edge(2,2,headport='se',tailport='ne')
G.add_edge(1,2,label='1-sp')

im = draw(G, layout='circo')
im
```

which gives this output:

![index](https://user-images.githubusercontent.com/208536/46831037-8be16280-cda2-11e8-95fb-d374ffcbc3e9.png)

thanks for any help!

**Comment by RafayAK** [comment]
Hey, did you find a way to add Latex labels? Stuck on the same problem

**Comment by galenwilkerson** [comment]
Hi, I don't think I found a solution.  best of luck

**Comment by chebee7i** [comment]
While I appreciate the simplicity that matplotlib has for specifying LaTeX as part of text, if you are building graphs and want more sophisticated math, then I think there are better tools for that. Notably, TiKZ. It's also pretty straightforward to write a converter from a NetworkX graph to a basic TiKZ graph that you can go through the manipulate/compile/view cycle.

Other examples:
https://tex.stackexchange.com/questions/13675/use-graphviz-within-tex
http://www.tcs.uni-luebeck.de/downloads/mitarbeiter/tantau/2012-gd-presentation.pdf

If you want static web displays, `pdf2svg` works well.  I don't think the TeX world has a nice solution if you want to highlight certain nodes on mouse hover or do other sorts of HTML/CSS interactions, sadly.

**Comment by chebee7i** [comment]
By closing this, I don't mean that it isn't a good idea, but my time on this project went away long ago. In principle, I'd guess it might be possible to hook into what matplotlib does and generate standalone node labels that are included as nodes in graphviz. For example, https://stackoverflow.com/a/8077158. But this is quite messy and bound to run into layout issues.  I think TikZ is a far superior solution.
