### ISSUE TITLE
error installing on kaggle kernel

### ISSUE THREAD

**Issue by galenwilkerson** [chebee7i/nxpd#13]
hi,

trying to install from a kaggle kernel, doesn't seem to find your package,

So, I've tried the standard way to install on kaggle,
https://www.kaggle.com/docs/kernels#modifying-a-kernel-specific-environment

and I get the attached image:

![screenshot_2018-11-03_07-14-42](https://user-images.githubusercontent.com/208536/47948810-4abf1700-df38-11e8-941a-3edb61dfa43b.png)

thanks for any help!

**Comment by galenwilkerson** [comment]
OK, figured it out.  Just entered 'nxpd' instead of the user/package name and it worked.

![screenshot_2018-11-03_07-18-25](https://user-images.githubusercontent.com/208536/47948841-d89b0200-df38-11e8-9672-9d6ce759ed71.png)

**Comment by chebee7i** [comment]
Yeah, that probably grabs it from PyPI.
