### ISSUE TITLE
Temporary files. 

### ISSUE THREAD

**Issue by rainwoodman** [chebee7i/nxpd#5]
Sorry, one more as I scan through the code. I am not sure if this one make much sense. 

Apparently all of the graphviz executables nxpd uses can read from stdin. We can likely do away with the temp files with `.communicate` . I wonder why original `pydot` chose to write to a temp file though.

However, in a longer term maybe we want to avoid `spawn`/`fork`/`exec` all together; they won't reliably work, for example, in a MPI program. -- I don't quite see why one would be visualizing graphs in a MPI program though.

**Comment by chebee7i** [comment]
I'm not too interested in rewriting parts of pydot in this project, but in principle, I think what you propose sounds good. I'm hoping pydot development will pick up soon.

**Comment by rainwoodman** [comment]
Pydot does look quite stalled indeed.
